site_name: "Cybergod RPG"
site_description: Tabletop RPG project page
site_author: Mikko Lainio

# Nav with Awesome Pages plugin
nav:
  - Introduction: introduction
  - Systems: systems
  - Character Creation: character-creation
  - Factions: factions
  - Game Mastering: gamemastering
  - NPC DB: npc-db

# OLD nav
# nav:
#   - Introduction:
#     - introduction/index.md
#     - Themes:      
#       - Utopia and Dystopia: introduction/utopia-and-dystopia.md
#       - Moral Dilemmas: introduction/moral-dilemmas.md
#       - Humanity and Artificial Life: introduction/humanity-and-artificial-life.md
#       - Psionics and Otherworldly Horror: introduction/psionics-and-horror.md
#       - Inspirations: introduction/inspirations.md
#   - Systems:
#     - Core Mechanics: systems/core-mechanics.md
#     - Combat: systems/combat.md
#     - Cyber Warfare: systems/cyber-warfare.md
#   - Character Creation:
#     - character-creation/index.md
#     - Persona: character-creation/persona.md
#     - Frame: character-creation/frame.md
#     - Gear: character-creation/gear.md
#   - Factions:
#     - factions/index.md
#     - Core:
#       - factions/core/index.md
#       - Advanced Regulator Corps (ARC): factions/core/arc.md
#       - Section 12: factions/core/section-12.md
#       - The Syndicate: factions/core/syndicate.md
#     - Ideological:
#       - factions/ideological/index.md
#       - Order of the Void: factions/ideological/order-of-the-void.md
#       - Radical X: factions/ideological/radical-x
#     - Mercenary:
#       - factions/mercenary/index.md
#       - Atlas Global Defense (AGD): factions/mercenary/agd.md
#       - The Cyberweavers: factions/mercenary/cyberweavers.md
#   - Game Mastering:
#     - gamemastering/index.md
#     - Story Seeds: gamemastering/story-seeds.md
#     - Progression: gamemastering/progression.md
#     - Merits: gamemastering/merits.md
#     - Enemies and NPC's:
#       - gamemastering/npc.md
#   - NPC DB:
    # - Baselines:
    #   - gamemastering/npc-db/baselines/index.md
    #   - Security Forces: gamemastering/npc-db/baselines/security-forces.md
    #   - Soldier: gamemastering/npc-db/baselines/soldier.md
    #   - Heavy Trooper: gamemastering/npc-db/baselines/heavy-trooper.md
    # - Drones:
    #   - gamemastering/npc-db/drones/index.md
    #   - Scout: gamemastering/npc-db/drones/scout-drone.md
    #   - R-LER: gamemastering/npc-db/drones/drone-rler.md
    # - Faction Encounters:
    #   - gamemastering/npc-db/factions/index.md
    #   - ARC:
    #     - Bulwark: gamemastering/npc-db/factions/arc-bulwark.md
    #     - Ghost: gamemastering/npc-db/factions/arc-ghost.md
    #     - Hunter: gamemastering/npc-db/factions/arc-hunter.md
    #   - Section 12:
    #     - Operator: gamemastering/npc-db/factions/section12-operator.md
    #     - Protector: gamemastering/npc-db/factions/section12-protector.md
    #     - Sentinel: gamemastering/npc-db/factions/section12-sentinel.md
    #   - Syndicate:
    #     - Puccini Guardian: gamemastering/npc-db/factions/syndicate-guardian.md
    #     - Shosuro Ronin: gamemastering/npc-db/factions/syndicate-ronin.md
    #     - Wu-Tai Stratagem: gamemastering/npc-db/factions/syndicate-stratagem.md
    #     - Radinovich Tzar: gamemastering/npc-db/factions/syndicate-tzar.md
    #   - Order of the Void:
    #     - Blessed Disciple: gamemastering/npc-db/factions/order-disciple.md
    #     - Blessed Harbinger: gamemastering/npc-db/factions/order-harbinger.md
    #     - Blessed Paladin: gamemastering/npc-db/factions/order-paladin.md
    #     - Zombified Civilian: gamemastering/npc-db/factions/order-zombie.md
    #   - Radical X:
    #     - Avenger: gamemastering/npc-db/factions/radical-x-avenger.md
    #     - Berserker: gamemastering/npc-db/factions/radical-x-berserker.md
    #     - Martyr: gamemastering/npc-db/factions/radical-x-martyr.md
    #   - AGD:
    #     - Colossus: gamemastering/npc-db/factions/agd-colossus.md
    #     - Reaper: gamemastering/npc-db/factions/agd-reaper.md
    #     - Soldat: gamemastering/npc-db/factions/agd-soldat.md
    #   - Cyberweavers:
        # - Adept: gamemastering/npc-db/factions/weaver-adept
        # - Shadow: gamemastering/npc-db/factions/weaver-shadow
        # - Virtual: gamemastering/npc-db/factions/weaver-virtual

extra_css:
  - stylesheets/extra.css

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    
    features:
      - navigation.indexes
      - navigation.top
      - navigation.tabs
      - toc.follow

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - tags
  - search
  - roamlinks
  - awesome-pages
 # - blog
  # - rss:
  #     match_path: blog/posts/.* 
  #     date_from_meta:
  #       as_creation: date
  #     categories:
  #       - categories
  #       - tags

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
