site_name: "Cybergod RPG"
site_description: Tabletop RPG project page
site_author: Mikko Lainio
copyright: Copyright &copy; 2014 - 2024 - Mikko Lainio

# Nav with Awesome Pages plugin

extra_css:
  - stylesheets/extra.css

theme:
    name: 'material'
    logo: assets/logo.png
    favicon: assets/favicon.png
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
    features:
      - navigation.indexes
      - navigation.top
      - navigation.tabs
      - navigation.footer
      - toc.follow

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - tags
  - search
  - roamlinks
  - awesome-pages
 # - blog
  # - rss:
  #     match_path: blog/posts/.* 
  #     date_from_meta:
  #       as_creation: date
  #     categories:
  #       - categories
  #       - tags

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
