site_name: "Cybergod RPG"
site_description: Tabletop RPG project page
site_author: Mikko Lainio
nav:
  - Introduction:
    - introduction/introduction.md
    - Themes:
      - introduction/themes.md
      - Utopia and Dystopia: introduction/utopia-and-dystopia.md
      - Moral Dilemmas: introduction/moral-dilemmas.md
      - Humanity and Artificial Life: introduction/humanity-and-artificial-life.md
      - Psionics and Otherworldly Horror: introduction/psionics-and-horror.md
      - Inspirations: introduction/inspirations.md
  - Systems:
    - systems/core-mechanics.md
    - Combat: systems/combat.md
    - Cyber Warfare: systems/cyber-warfare.md
  - Character Creation:
    - character-creation/character-creation.md
    - Persona: character-creation/persona.md
    - Frame: character-creation/frame.md
    - Gear: character-creation/gear.md
  - Factions:
    - factions/factions.md
    - Core:
      - factions/core/core.md
      - Advanced Regulator Corps (ARC): factions/core/arc.md
      - Section 12: factions/core/section-12.md
      - The Syndicate: factions/core/syndicate.md
    - Ideological:
      - factions/ideological/ideological.md
      - Order of the Void: factions/ideological/order-of-the-void.md
      - Radical X: factions/ideological/radical-x
    - Mercenary:
      - factions/mercenary/mercenary.md
      - Atlas Global Defense (AGD): factions/mercenary/agd.md
      - The Cyberweavers: factions/mercenary/cyberweavers.md
  - Game Mastering:
    - gamemastering/gamemastering.md
    - Story Seeds: gamemastering/story-seeds.md
    - Progression: gamemastering/progression.md
    - Merits: gamemastering/merits.md
    - Enemies and NPC's: gamemastering/npc.md

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    
    features:
      - navigation.indexes
      - toc.follow

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
 # - blog
  # - rss:
  #     match_path: blog/posts/.* 
  #     date_from_meta:
  #       as_creation: date
  #     categories:
  #       - categories
  #       - tags

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
